mod auth;
mod language;
mod module;
mod phrase;
mod phrase_type;
mod project;
mod screenshot;
mod term;
mod translation;
mod user;

pub use auth::auth_routes;
pub use language::language_routes;
pub use module::module_routes;
pub use phrase::phrase_routes;
pub use project::project_routes;
pub use screenshot::screenshot_routes;
pub use term::term_routes;
pub use translation::translation_routes;
pub use user::user_routes;
