-- 预填充词条类型数据
INSERT INTO i18n_phrase_types (name, description, icon, crt_by) VALUES
('button', '按钮文本', 'mdi-button-pointer', 1),
('menu', '菜单项', 'mdi-menu', 1),
('title', '页面标题', 'mdi-format-title', 1),
('label', '标签文本', 'mdi-label', 1),
('placeholder', '输入框占位符', 'mdi-form-textbox', 1),
('tooltip', '工具提示', 'mdi-tooltip-text', 1),
('message', '普通消息', 'mdi-message-text', 1),
('error', '错误信息', 'mdi-alert-circle', 1),
('success', '成功信息', 'mdi-check-circle', 1),
('warning', '警告信息', 'mdi-alert', 1),
('notification', '通知消息', 'mdi-bell-ring', 1),
('text', '普通文本', 'mdi-text', 1),
('link', '链接文本', 'mdi-link', 1),
('tab', '选项卡', 'mdi-tab', 1),
('filter', '筛选条件', 'mdi-filter', 1),
('column', '表格列名', 'mdi-table-column', 1),
('validation', '验证消息', 'mdi-shield-alert', 1),
('email', '邮件内容', 'mdi-email', 1),
('push', '推送通知', 'mdi-cellphone-message', 1),
('log', '日志消息', 'mdi-text-box', 1),
('api', 'API响应消息', 'mdi-api', 1),
('other', '其他类型', 'mdi-dots-horizontal', 1);